### ISSUE TITLE
SSLException

### ISSUE THREAD

**Issue by gvolpe** [augustjune/canoe#35]
Hi, thanks for making this library! 

I'm trying to get the simple [Greetings](https://github.com/augustjune/canoe/blob/master/examples/src/main/scala/samples/Greetings.scala) example working with a bot I have created but I've observed an `SSLException` in the logs after many POST requests are attempted. 

Have you seen this error before? I've never used the Telegram Bot API so maybe I'm doing something wrong?

```
17:47:55.348 [ioapp-compute-0] DEBUG org.http4s.client.blaze.Http1Connection - Beginning request: POST https://api.telegram.org/bot[MY_TOKEN]/getUpdates
17:47:55.348 [ioapp-compute-3] DEBUG org.http4s.blazecore.IdleTimeoutStage - Starting idle timeout stage with timeout of 60000 ms
17:47:56.410 [InnocuousThread-10] DEBUG org.http4s.blaze.pipeline.stages.SSLStage - SSL Read Request Status: Status = OK HandshakeStatus = NOT_HANDSHAKING
bytesConsumed = 521 bytesProduced = 492, java.nio.HeapByteBuffer[pos=492 lim=16921 cap=16921]
17:47:56.410 [InnocuousThread-10] DEBUG org.http4s.blaze.pipeline.stages.SSLStage - SSL Read Request Status: Status = BUFFER_UNDERFLOW HandshakeStatus = NOT_HANDSHAKING
bytesConsumed = 0 bytesProduced = 0, java.nio.HeapByteBuffer[pos=0 lim=16921 cap=16921]
17:47:56.410 [InnocuousThread-10] DEBUG org.http4s.blaze.pipeline.stages.SSLStage - SSL Read Request Status: Status = BUFFER_UNDERFLOW HandshakeStatus = NOT_HANDSHAKING
bytesConsumed = 0 bytesProduced = 0, java.nio.HeapByteBuffer[pos=0 lim=16921 cap=16921]
17:47:56.412 [scala-execution-context-global-225] DEBUG org.http4s.client.blaze.Http1Connection - Resetting org.http4s.client.blaze.Http1Connection after completing request.
17:47:56.420 [scala-execution-context-global-225] DEBUG org.http4s.blazecore.IdleTimeoutStage - Shutting down idle timeout stage
17:47:56.420 [scala-execution-context-global-225] DEBUG org.http4s.blazecore.IdleTimeoutStage - Shutting down.
17:47:56.420 [scala-execution-context-global-225] DEBUG org.http4s.blazecore.IdleTimeoutStage - Removed mid-stage: IdleTimeoutStage
17:47:56.421 [scala-execution-context-global-225] DEBUG org.http4s.client.blaze.ReadBufferStage - Shutting down.
17:47:56.429 [scala-execution-context-global-225] DEBUG org.http4s.blaze.pipeline.stages.SSLStage - Error while closing SSL Engine
javax.net.ssl.SSLException: Inbound closed before receiving peer's close_notify: possible truncation attack?
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1647)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1615)
	at sun.security.ssl.SSLEngineImpl.closeInbound(SSLEngineImpl.java:1542)
	at org.http4s.blaze.pipeline.stages.SSLStage.stageShutdown(SSLStage.scala:61)
	at org.http4s.blaze.pipeline.Tail.closePipeline(Stages.scala:78)
	at org.http4s.blaze.pipeline.Tail.closePipeline$(Stages.scala:77)
	at org.http4s.blaze.pipeline.stages.SSLStage.closePipeline(SSLStage.scala:41)
	at org.http4s.blaze.pipeline.Tail.closePipeline(Stages.scala:81)
	at org.http4s.blaze.pipeline.Tail.closePipeline$(Stages.scala:77)
	at org.http4s.client.blaze.ReadBufferStage.closePipeline(ReadBufferStage.scala:13)
	at org.http4s.blaze.pipeline.Tail.closePipeline(Stages.scala:81)
	at org.http4s.blaze.pipeline.Tail.closePipeline$(Stages.scala:77)
	at org.http4s.client.blaze.Http1Connection.closePipeline(Http1Connection.scala:25)
	at org.http4s.client.blaze.Http1Connection.shutdownWithError(Http1Connection.scala:83)
	at org.http4s.client.blaze.Http1Connection.stageShutdown(Http1Connection.scala:54)
	at org.http4s.client.blaze.Http1Connection.shutdown(Http1Connection.scala:52)
	at org.http4s.client.PoolManager.$anonfun$invalidate$1(PoolManager.scala:313)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:87)
	at cats.effect.internals.IORunLoop$.startCancelable(IORunLoop.scala:41)
	at cats.effect.internals.IOBracket$BracketStart.run(IOBracket.scala:86)
	at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:70)
	at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:36)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.super$startLoop(TrampolineEC.scala:93)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.$anonfun$startLoop$1(TrampolineEC.scala:93)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:93)
	at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
	at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:44)
	at cats.effect.internals.Callback$AsyncIdempotentCallback.apply(Callback.scala:137)
	at cats.effect.internals.Callback$AsyncIdempotentCallback.apply(Callback.scala:124)
	at org.http4s.client.blaze.Http1Connection.parsePrelude(Http1Connection.scala:296)
	at org.http4s.client.blaze.Http1Connection.$anonfun$readAndParsePrelude$1(Http1Connection.scala:189)
	at org.http4s.client.blaze.Http1Connection.$anonfun$readAndParsePrelude$1$adapted(Http1Connection.scala:188)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:447)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
17:47:56.431 [scala-execution-context-global-225] DEBUG org.http4s.blaze.channel.nio2.ByteBufferHead - Shutting down.
17:47:56.432 [scala-execution-context-global-225] DEBUG org.http4s.blaze.channel.nio2.ByteBufferHead - doClosePipeline(None)
17:47:56.432 [scala-execution-context-global-225] DEBUG org.http4s.client.blaze.Http1Connection - Shutting down.
17:47:56.435 [scala-execution-context-global-225] DEBUG org.http4s.client.PoolManager - Invalidated connection, no pending requests. Shrinking pool: curAllocated=0 idleQueues.size=0 waitQueue.size=0 maxWaitQueueLimit=256 closed=false
17:47:56.471 [ioapp-compute-0] INFO org.http4s.client.PoolManager - Shutting down connection pool: curAllocated=0 idleQueues.size=0 waitQueue.size=0 maxWaitQueueLimit=256 closed=false
org.http4s.client.UnexpectedStatus: unexpected HTTP status: 409 Conflict

Exception: sbt.TrapExitSecurityException thrown from the UncaughtExceptionHandler in thread "run-main-0"
```

**Comment by gvolpe** [comment]
Update: The greetings example works now but I always get this exception when I hit `Ctrl+C` to close the sbt session.

**Comment by augustjune** [comment]
Thank you for using this library :)
I didn't encounter this error during my tests, but I will check the cases you described and let you know what I got

**Comment by augustjune** [comment]
I was able to collect some info about this issue.
Running bot from SBT I get the same error in the following scenario:
1. Bot is running
2. I hit `Ctrl+C`
3. I run the bot again
4. Exception is raised but the application is still running

Such behavior is actually caused by SBT, since SBT console doesn't really stop the app when you hit `Ctrl+C` (even though it looks like it does). I noticed it during debugging, but you can also observe that the bot is still up. Having that, when you run the application again new bot is stood up and that causes conflict by Telegram side, raising SSL Exception and shutting down one of the bots. 
Does this make sense in your case?

I could not reproduce the error with idle bot though. How much time does it take before the error is raised?

**Comment by gvolpe** [comment]
Thanks for investigating this. I believe SBT can cause such problem since it's quite buggy.

I'll see if I can reproduce the other issue. It used to happen the first time when the bot wasn't working for some reason, not sure it's happening anymore.

**Comment by oskin1** [comment]
@augustjune, Hi, thank you for such a library!
I'm experiencing the same problem either when running under SBT or running a jar.
I'm always getting the same error emmidiately when trying to run an app:
```
14:49:56.533 [zio-default-async-6-1014328909] DEBUG org.http4s.client.PoolManager - Requesting connection: curAllocated=0 idleQueues.size=0 waitQueue.size=0 maxWaitQueueLimit=256 closed=false
14:49:56.543 [zio-default-async-6-1014328909] DEBUG org.http4s.client.PoolManager - Active connection not found. Creating new one. curAllocated=0 idleQueues.size=0 waitQueue.size=0 maxWaitQueueLimit=256 closed=false
14:49:56.652 [scala-execution-context-global-28] DEBUG org.http4s.blaze.channel.nio2.ByteBufferHead - Starting up.
14:49:56.653 [scala-execution-context-global-28] DEBUG org.http4s.blaze.channel.nio2.ByteBufferHead - Stage ByteBufferHead sending inbound command: Connected
14:49:56.653 [scala-execution-context-global-28] DEBUG org.http4s.blaze.pipeline.stages.SSLStage - Starting up.
14:49:56.653 [scala-execution-context-global-28] DEBUG org.http4s.blaze.pipeline.stages.SSLStage - Stage SSLStage sending inbound command: Connected
14:49:56.654 [scala-execution-context-global-28] DEBUG org.http4s.client.blaze.ReadBufferStage - Stage started up. Beginning read buffering
14:49:56.676 [scala-execution-context-global-28] DEBUG org.http4s.blaze.pipeline.stages.SSLStage - SSL Read Request Status: Status = OK HandshakeStatus = NEED_WRAP
bytesConsumed = 0 bytesProduced = 0, java.nio.HeapByteBuffer[pos=0 lim=16709 cap=16709]
14:49:56.679 [scala-execution-context-global-28] DEBUG org.http4s.client.blaze.ReadBufferStage - Stage ReadBufferStage sending inbound command: Connected
14:49:56.679 [scala-execution-context-global-28] DEBUG org.http4s.client.blaze.Http1Connection - Starting up.
14:49:56.694 [zio-default-async-2-1014328909] DEBUG org.http4s.client.blaze.Http1Connection - Connection was idle. Running.
14:49:56.706 [zio-default-async-2-1014328909] DEBUG org.http4s.client.blaze.Http1Connection - Beginning request: POST https://api.telegram.org/bot<my_token>/getUpdates
14:49:56.785 [zio-default-async-8-1014328909] DEBUG org.http4s.blazecore.IdleTimeoutStage - Starting idle timeout stage with timeout of 60000 ms
14:49:56.799 [zio-default-async-9-1014328909] DEBUG org.http4s.blaze.pipeline.stages.SSLStage - SSL Read Request Status: Status = BUFFER_UNDERFLOW HandshakeStatus = NEED_UNWRAP
bytesConsumed = 0 bytesProduced = 0, java.nio.HeapByteBuffer[pos=0 lim=16709 cap=16709]
14:49:56.801 [scala-execution-context-global-28] DEBUG org.http4s.blazecore.IdleTimeoutStage - Shutting down idle timeout stage
14:49:56.801 [scala-execution-context-global-28] DEBUG org.http4s.blazecore.IdleTimeoutStage - Shutting down.
14:49:56.802 [scala-execution-context-global-28] DEBUG org.http4s.client.blaze.ReadBufferStage - Shutting down.
14:49:56.802 [scala-execution-context-global-28] DEBUG org.http4s.blaze.pipeline.stages.SSLStage - Error while closing SSL Engine
javax.net.ssl.SSLException: closing inbound before receiving peer's close_notify
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:129)
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
```

How could it be fixed?
